version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - '80:8000'
        volumes:
            - './:/var/www/html'
        networks:
            - petshop-net
        restart: unless-stopped
        depends_on:
            - mysql
            - mysql-test
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password@Pass.123'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'petshop-db'
            MYSQL_USER: 'pet'
            MYSQL_PASSWORD: 'password@Pass.456'
        volumes:
            - 'petshop-db-mysql:/var/lib/mysql'
        networks:
            - petshop-net
    mysql-test:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password@Pass.123'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: 'petshop-db'
            MYSQL_USER: 'pet'
            MYSQL_PASSWORD: 'password@Pass.456'
        volumes:
            - 'petshop-db-mysql-test:/var/lib/mysql'
        networks:
            - petshop-net
networks:
    petshop-net:
        driver: bridge
volumes:
    petshop-db-mysql:
        driver: local
    petshop-db-mysql-test:
        driver: local
